# pip install localstack==2.2.0
# for python 3.8+
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:2.2.0
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DOCKER_SOCK=/var/run/docker.sock
      - DEBUG=0
      - PERSISTENCE=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./boot.sh:/etc/localstack/init/boot.d/boot.sh
      - ./ready.sh:/etc/localstack/init/ready.d/ready.sh
      - ./shutdown.sh:/etc/localstack/init/shutdown.d/shutdown.sh
      - localstack_pods:/pods

volumes:
  localstack_pods: